[package]
name = "watfaq-netstack"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"


[features]
default = []

[dependencies]
smoltcp = { version = "0.13", default-features = false, features = [
    "std",
    "log",
    "medium-ip",
    "proto-ipv4",
    "proto-ipv6",
    "socket-tcp",
    "socket-udp",
    "socket-icmp",
    "async",
    "socket-tcp-cubic",
]}
bytes = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
log = "0.4"
rand = "0.8"
etherparse = "0.21"